
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/bo.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/c.f.txt   public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/cb.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/cc.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/ct.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/fc.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/fv.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/gc.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/ho.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/kc.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/kw.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/lb.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/lc.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/lf.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/lh.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/mw.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/nf.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/oj.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/pa.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/pl.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/rb.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/rr.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/rs.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/s.f.txt   public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/sb.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/si.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/sm.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/w.f.txt   public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/commodities/wi.f.txt  public/data

cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/lme/ca_c.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/lme/co_c.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/lme/ni_c.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/lme/pb_c.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/lme/sn_c.f.txt  public/data
cp ./source_data/Prices/Stooq/2021-04-29/Daily/world/lme/zs_c.f.txt  public/data

cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/bonds/10usy.b.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/bonds/30usy.b.txt  public/data

cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/currencies/major/audusd.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/currencies/major/cadusd.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/currencies/major/chfusd.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/currencies/major/eurusd.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/currencies/major/gbpusd.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/currencies/major/jpyusd.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/currencies/major/nzdusd.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/currencies/other/czkusd.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/currencies/other/dkkusd.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/currencies/other/hufusd.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/currencies/other/mxnusd.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/currencies/other/nokusd.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/currencies/other/plnusd.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/currencies/other/sekusd.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/currencies/other/sgdusd.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/currencies/other/tryusd.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/currencies/other/usdhkd.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/currencies/other/zarusd.txt  public/data

cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/indices/^cac.txt   public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/indices/^dax.txt   public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/indices/^dji.txt   public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/indices/^ftm.txt   public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/indices/^hsi.txt   public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/indices/^ibex.txt  public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/indices/^ndx.txt   public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/indices/^nkx.txt   public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/indices/^spx.txt   public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/indices/^sti.txt   public/data
cp ./source_data/Prices/Stooq/2023-05-03/Daily/world/indices/^ukx.txt   public/data
